spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eevolution
    username: eevolution
    password: eevolution
    driverClassName: org.postgresql.Driver

codebuilder.exportTables: AD_Table,AD_Column