server:
  port: 9080
  
spring:
  application:
    name: simpleservice

  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0    
    
  cloud:
    config:
      uri: http://localhost:8888    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka