server:
  port: 9080
  
spring:
  application:
    name: simpleservice
    
  cloud:
    config:
      uri: http://localhost:8888    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka