server:
  port: 9411
  
spring:
  application:
    name: sleuth
    
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
  client:
    serviceUrl:
      defaultZone: ${eureka-service-url:http://localhost:8761/eureka/}