rabbitmq:
  image: rabbitmq:3.7.4-management
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  ports:
    - 5672:5672
    - 15672:15672
  
#mysql:
#  image: mysql:8.0.4
#  environment:
#    - MYSQL_ROOT_PASSWORD=password  
#  ports:
#    - 3306:3306
