server:
  port: 8000
  
spring:
  application:
    name: gateway
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server  

eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}  
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka-service-url:http://localhost:8761/eureka/}

management:
  security:
    enabled: false
        
zuul:
  routes:
    sleuth:
      path: /zipkin/**
    service-ribbon:
      path: /api/ribbon/**
    service-feign:
      path: /api/feign/**
    simpleservice:
      path: /api/direct/**            