app:
  server: 192.168.99.100
  db: logs3
 
skymonitor:
  threads: 5
  path: /Users/xiangwanhong/logs3
  haustedTime: -1
  
spring:
  datasource:
    url: jdbc:mysql://${app.server}/${app.db}
    driverClassName: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    username: root
    password: password
  jpa:
#    showSql: true
    hibernate:
      #create|create-drop|update|validate
      ddlAuto: update
      formatSql: true    
    