rabbitmq:
  image: rabbitmq:3.7.4-management
  environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=admin
  ports:
    - 5672:5672
    - 15672:15672
  
mysql:
  image: mysql:8.0.4
  environment:
    - MYSQL_ROOT_PASSWORD=password  
  ports:
    - 3306:3306
    
eureka-server:
  image: myfly.org/eureka-server
  environment:
    - eureka-service-url=http://localhost:80/eureka
  ports:
    - 8761:80

config-server:
  image: myfly.org/config-server
  environment:
    - rabbitmq-server=rabbitmq
    - rabbitmq-port=5672
    - eureka-service-url=http://eureka-server:80/eureka
  ports:
    - 8800:80
  links:
    - rabbitmq
    - eureka-server
    
gateway-server:
  image: myfly.org/gateway-server
  environment:
    - eureka-service-url=http://eureka-server:80/eureka
  ports:
    - 80:80
  links:
    - eureka-server
    
sleuth-server:
  image: myfly.org/sleuth-server
  environment:
    - eureka-service-url=http://eureka-server:80/eureka
  ports:
    - 9411:80
  links:
    - eureka-server
    
ui-libs:
  image: myfly.org/ui-libs
  environment:
    - eureka-service-url=http://eureka-server:80/eureka
  ports:
    - 8100:80
  links:
    - eureka-server    