server:
  port: 9082
  
spring:
  application:
    name: service-feign
    
  cloud:
    config:
      uri: http://localhost:8888    

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka