server:
  port: 8800
  
spring:
  cloud:
    config:
      server:
        label: spring-boot-1.4
        git:
          uri: https://github.com/xwh123807/org.myfly/
          searchPaths: myfly.cloud/myfly-config-repo
        native:
          searchLocations: classpath:/config
  profiles:
    active: native  
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka   
      
management:
  security:
    enabled: false
    
