server:
  port: 8888

spring:
  cloud:
    config:
      server:
         git:
           uri: classpath:/config/
#        native:
#          searchLocations: classpath:/config/
#        git:
#          uri: https://github.com/xwh123807/microapps.git
#          searchPaths: org.myfly.platform.parent/myfly.cloud/myfly-config-repo

#eureka:
#  instance:
#    hostname: localhost
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:18761/eureka/          