redis:
  image: redis:4.0
  ports: 
   - "6379:6379"
elasticsearch:
  image: elasticsearch:5.6.8
  command: ["-Epath.conf=/configdir/elasticsearch"]
  ports:
   - "9200:9200"
   - "9300:9300"
  volumes:
   - $PWD:/configdir
mysql:
  image: mysql:8.0
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
  volumes:
   - /tmp/mysql:/var/lib/mysql
   - ./mysql:/etc/mysql/conf.d
rabbitmq:
  image: rabbitmq:3.7.4-management
  ports:
   - "5672:5672"
   - "15672:15672"