redis:
  image: redis:4.0.9
  ports: 
   - "6379:6379"
elasticsearch:
  image: elasticsearch:2.4.3
  ports:
   - "9200:9200"
   - "9300:9300"
mysql:
  image: mysql:8.0.4
  ports:
   - "3306:3306"
  environment:
   - MYSQL_ROOT_PASSWORD=password
  volumes:
   - /tmp/data/mysql:/var/lib/mysql
   - ./mysql:/etc/mysql/conf.d
rabbitmq:
  image: rabbitmq:3.7.4-management
  ports:
   - "5672:5672"
   - "15672:15672"