server:
  port: 8761
  
eureka:
  instance:
    hostname: ${spring.cloud.client.ipAddress}
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${eureka-service-url:http://localhost:8761/eureka/}

management:
  security:
    enabled: false