server:
  port: 8000
  
spring:
  application:
    name: gateway
    
  cloud:
    config:
      uri: http://localhost:8888    

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
        
zuul:
  routes:
    api-a:
      path: /api/ribbon/**
      serivceId: service-ribbon
      stripPrefix: true
    api-b:
      path: /api/feign/**
      serivceId: service-feign
      stripPrefix: true
    api-c:
      path: /api/direct/**
      servieId: simpleservice
      stripPrefix: true
            