server:
  port: 8000
  
spring:
  application:
    name: gateway
    
  cloud:
    config:
      uri: http://localhost:8888    

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  security:
    enabled: false
        
zuul:
  routes:
    service-ribbon:
      path: /api/ribbon/**
    service-feign:
      path: /api/feign/**
    simpleservice:
      path: /api/direct/**            