server:
  port: 9081
  
spring:
  application:
    name: service-ribbon
    
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0       
    
management:
  security:
    enabled: false 

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka